# Generated by Django 5.0.7 on 2024-08-13 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_contact_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='product_name',
            new_name='name',
        ),
    ]
