# Generated by Django 5.0.7 on 2024-08-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_orders_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='emial',
            new_name='email',
        ),
    ]
